#!/usr/bin/env bash
# E2E: `zigapagos init` scaffolds the frontmatter a page NEEDS, and no more.
#
# src/context/Page.zig gives `author` (""), `date` (DateTime.epoch) and `draft`
# (false) defaults — only `title` and `layout` are required. Every init template
# wrote all five anyway, so the scaffold modelled three optional fields as
# obligatory and every site started from it inherited that (issue #57: a 404 page
# with an author and a publication date).
#
# The trim is not uniform, which is the whole reason this is a test and not a
# grep. `.date` is load-bearing exactly where a layout reads it: blog.shtml and
# devlog-archive.shtml print `$loop.it.date.format(...)` for each subpage, and
# blog.xml emits it as `pubDate`. So the dated collection ENTRIES keep their
# dates and the pages nothing lists lose them. Asserting only the removals would
# pass just as well on a scaffold that dropped every date and quietly emptied the
# blog listing's date column, so both directions are asserted here.
#
# The build at the end is the substantive claim: a page carrying only `.title`
# and `.layout` builds, which is what makes the trim safe rather than merely
# shorter.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
REPO="$(pwd)"

BIN="$REPO/zig-out/bin/zigapagos"
if [ ! -x "$BIN" ]; then
  echo "building zigapagos..."
  mise exec -- zig build
fi

WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT

( cd "$WORK" && "$BIN" init ) > "$WORK/init.log" 2>&1 \
  || { echo "FAIL: zigapagos init exited non-zero"; cat "$WORK/init.log"; exit 1; }

fail() { echo "FAIL: $*"; exit 1; }

# Collect the scaffolded content files. A `for f in $(...)` split is deliberate
# here — these paths are generated by init and contain no spaces — but the list
# is checked for emptiness first, because an empty list would make every
# absence-assertion below pass without examining anything.
SMDS=()
while IFS= read -r f; do SMDS+=("$f"); done < <(find "$WORK/content" -name '*.smd' | sort)
(( ${#SMDS[@]} >= 9 )) || fail "expected at least 9 scaffolded .smd files, found ${#SMDS[@]}"

# 1. Fields with defaults are not scaffolded at all.
#    `.author` is read by no init layout; `.draft = false` restates the default.
for f in "${SMDS[@]}"; do
  rel="${f#"$WORK"/}"
  ! grep -q '^\.author' "$f" || fail "$rel scaffolds .author, which no init layout reads and which defaults to \"\""
  ! grep -q '^\.draft' "$f" || fail "$rel scaffolds .draft, which already defaults to false"
done

# 2. `.date` only where a layout prints it.
#    Undated: the two standalone pages and the two section indexes — nothing
#    loops over them, so their dates were never rendered anywhere.
for rel in content/index.smd content/about.smd content/blog/index.smd content/devlog/index.smd; do
  [ -f "$WORK/$rel" ] || fail "$rel missing from the scaffold"
  ! grep -q '^\.date' "$WORK/$rel" || fail "$rel scaffolds .date, but no layout renders this page's date"
done
#    Dated: the collection entries blog.shtml / blog.xml / devlog-archive.shtml
#    render. Dropping these would silently empty the listing's date column.
for rel in content/blog/first-post/index.smd content/blog/second-post.smd \
           content/blog/code-blocks.smd content/devlog/1989.smd content/devlog/1990.smd; do
  [ -f "$WORK/$rel" ] || fail "$rel missing from the scaffold"
  grep -q '^\.date' "$WORK/$rel" \
    || fail "$rel has no .date, but its listing layout renders one for every entry"
done

# 3. The trimmed scaffold still builds, and the dates that survived still render.
( cd "$WORK" && "$BIN" release ) > "$WORK/release.log" 2>&1 \
  || { echo "FAIL: zigapagos release failed on the scaffolded site"; cat "$WORK/release.log"; exit 1; }

for page in index.html about/index.html blog/index.html devlog/index.html; do
  [ -f "$WORK/public/$page" ] || fail "release emitted no public/$page"
done
grep -q 'January 01, 1990' "$WORK/public/blog/index.html" \
  || fail "the blog listing lost its formatted post dates"
grep -q 'Year 1989' "$WORK/public/devlog/index.html" \
  || fail "the devlog archive lost its formatted year dates"
# The RSS alternative reads $loop.it.date.formatHTTP(); an entry that lost its
# date would emit the epoch here rather than fail the build.
grep -q 'pubDate' "$WORK/public/blog/index.xml" \
  || fail "the blog feed emitted no pubDate"
! grep -qi 'Sample Author' -r "$WORK/public" \
  || fail "the built site still carries the scaffold's placeholder author"

echo "PASS: init scaffolds only required frontmatter + the dates its layouts render, and the result builds"
