#!/usr/bin/env bash
# Self-tests for tests/branding.sh.
#
# WHY A SELF-TEST. The branding gate now has real parsing in it — an inline
# opt-out marker with a required reason, balanced blocks, and a stale-marker
# rule (#60). A gate with parsing in it has a failure mode a gate with one grep
# does not: it can go PERMISSIVE without going red. A marker parser that
# accidentally exempts every line still prints PASS on a clean tree, and nothing
# in this repository would notice until someone shipped the upstream name.
# tests/meta/script-coverage.sh's header records two assertions that rotted
# exactly this way. So each rule below is pinned from BOTH sides: a tree the
# gate must accept, and the nearest tree it must reject.
#
# Each case is a THROWAWAY GIT REPOSITORY under $TMPDIR with the gate copied to
# tests/branding.sh, because the gate is `git grep` over tracked files and there
# is no way to feed it a fixture otherwise. Nothing here touches this checkout.
#
# Like the gate, this file never spells the needle out: it is assembled at
# runtime into $N and interpolated into fixtures, so this script is not a hit
# for the gate it tests. The gate deliberately does NOT exclude either file from
# its search — see its header — so a literal here would fail the real run.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

GATE="$PWD/tests/branding.sh"
N='zi''ne'
M='branding-ok:'

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

pass=0
fail=0
case_n=0

# Build a throwaway repo containing the gate plus the named fixture files, run
# the gate in it, and check the outcome. `git add` is given explicit paths (the
# repo convention), which is easy here because the caller names every fixture.
#
# $1 name, $2 expected exit (0 or 1), $3 substring the output must contain
# ("" = no requirement), then the fixture files already written into $d by the
# caller via `newcase`.
declare -a FIXTURES=()
d=""

newcase() {
  case_n=$((case_n + 1))
  d="$TMP/case$case_n"
  mkdir -p "$d/tests"
  cp "$GATE" "$d/tests/branding.sh"
  git -C "$d" init -q
  FIXTURES=(tests/branding.sh)
}

fixture() { # $1 relative path (content on stdin)
  mkdir -p "$d/$(dirname "$1")"
  cat >| "$d/$1"
  FIXTURES+=("$1")
}

check() { # $1 name, $2 expected exit, $3 required substring
  local name=$1 want=$2 needle=${3:-} out status
  git -C "$d" add -- "${FIXTURES[@]}"
  set +e
  out=$( cd "$d" && bash tests/branding.sh 2>&1 )
  status=$?
  set -e
  if [ "$status" -ne "$want" ]; then
    echo "FAIL: $name — expected exit $want, got $status"
    printf '%s\n' "$out" | sed 's/^/      /'
    fail=$((fail + 1))
    return
  fi
  if [ -n "$needle" ] && ! printf '%s\n' "$out" | grep -qF -- "$needle"; then
    echo "FAIL: $name — exit $status was right but the message never said '$needle'"
    printf '%s\n' "$out" | sed 's/^/      /'
    fail=$((fail + 1))
    return
  fi
  pass=$((pass + 1))
}

# ── The base behaviour the marker must not have weakened ─────────────────────

newcase
fixture docs/clean.md <<EOF
Zigapagos builds static sites.
EOF
check "a tree with no mention passes" 0 "PASS"

newcase
fixture docs/leak.md <<EOF
This page was generated by $N.
EOF
check "an unmarked mention fails" 1 "docs/leak.md"

newcase
fixture README.md <<EOF
A fork of $N.
EOF
check "the file allowlist still exempts wholesale attribution" 0 "PASS"

# ── The marker itself ────────────────────────────────────────────────────────

newcase
fixture CHANGELOG.md <<EOF
The fork-point tag is \`fork-point-$N-v0-11-2\`. <!-- $M naming the tag -->
EOF
check "a same-line marker with a reason sanctions the line" 0 "naming the tag"

newcase
fixture CHANGELOG.md <<EOF
The fork-point tag is \`fork-point-$N-v0-11-2\`. <!-- $M -->
EOF
check "a marker with no reason fails" 1 "with no reason"

newcase
fixture docs/tags.md <<EOF
<!-- ${M}begin the tag names are the subject of this passage -->
The fork point is tagged \`fork-point-$N-v0-11-2\`.
There is no other $N tag in this repository.
<!-- ${M}end -->
EOF
check "a block marker sanctions every line it spans" 0 "PASS"

newcase
fixture docs/tags.md <<EOF
<!-- ${M}begin the tag names are the subject of this passage -->
The fork point is tagged \`fork-point-$N-v0-11-2\`.
<!-- ${M}end -->
Elsewhere the generator is called $N, which it is not.
EOF
check "a mention outside the block is still caught" 1 "docs/tags.md:4"

newcase
fixture docs/tags.md <<EOF
<!-- ${M}begin the tag names are the subject of this passage -->
The fork point is tagged \`fork-point-$N-v0-11-2\`.
EOF
check "an unclosed block fails instead of exempting the file's tail" 1 "never closed"

newcase
fixture docs/tags.md <<EOF
The fork point is tagged \`fork-point-$N-v0-11-2\`.
<!-- ${M}end -->
EOF
check "a stray end fails" 1 "no matching"

newcase
fixture docs/tags.md <<EOF
<!-- ${M}begin outer -->
The fork point is tagged \`fork-point-$N-v0-11-2\`.
<!-- ${M}begin inner -->
<!-- ${M}end -->
EOF
check "a nested begin fails" 1 "nested"

newcase
fixture docs/reworded.md <<EOF
The fork point has its own tag. <!-- $M naming the tag -->
EOF
check "a marker that exempts nothing fails as stale" 1 "exempts nothing"

# ── A marker shown as an example is documentation, not an instruction ────────
# CLAUDE.md, CONTRIBUTING.md, ci.yml and docs/dx-backlog.md all spell the marker
# out to explain it. Without this rule the gate fails on its own documentation.

newcase
fixture docs/howto.md <<EOF
Write \`<!-- $M why -->\` on the line to sanction it.
EOF
check "a marker inside a code span is not a marker" 0 "PASS"

newcase
fixture docs/howto.md <<EOF
For a whole passage:

\`\`\`markdown
<!-- ${M}begin why -->
...
<!-- ${M}end -->
\`\`\`
EOF
check "a marker inside a fenced code block is not a marker" 0 "PASS"

newcase
fixture docs/howto.md <<EOF
Write \`<!-- $M why -->\` on the line to sanction it.
This generator is not called $N.
EOF
check "documenting the marker does not exempt a real mention" 1 "docs/howto.md:2"

# ── The gate must remain subject to its own search ───────────────────────────
# The previous version excluded itself with a ':!tests/branding.sh' pathspec AND
# spelled the needle out in its own comments. tests/confidentiality.sh records
# what that combination cost the first time. This pins that it cannot come back.

newcase
printf '\n# %s\n' "$N" >> "$d/tests/branding.sh"
check "the gate searches its own source" 1 "tests/branding.sh"

echo
if [ "$fail" -gt 0 ]; then
  echo "FAIL: $fail of $((pass + fail)) branding-gate self-tests failed"
  exit 1
fi
echo "PASS: $pass branding-gate self-tests"
