"use strict";
// Maps the host to its `@zigapagos/cli-<key>` package and returns the absolute
// path to the bundled `zigapagos` binary.
//
// This file is COMMITTED; the package.json beside it is generated by
// ../gen-packages.mjs from ./targets.json + build.zig.zon. targets.json is the
// npm side's copy of the release matrix and is gated against build/release.zig
// by ../check-targets.mjs (see tests/npm/targets.sh) — a stale copy here would
// publish a platform package resolving to a binary nobody built.
//
// Two distinct failures are reported differently on purpose, because the fix is
// different: an unsupported platform is permanent until a target is added to
// build/release.zig, while a missing optionalDependency is an install-flag
// problem the user can undo (`--no-optional` / `--omit=optional`).
const { existsSync } = require("node:fs");
const { basename, delimiter, dirname, join } = require("node:path");
const targets = require("./targets.json");

const PKG = "@zigapagos/cli";
const SUPPORTED = Object.fromEntries(targets.map((t) => [t.key, `${PKG}-${t.key}`]));

// Named reasons for common unsupported platforms make a deliberate gap read as
// such instead of looking like an omitted matrix row.
const WINDOWS_REASON =
  "Windows is not supported yet (upstream's WindowsWatcher.zig/wuffs.zig do not compile " +
  "on released Zig 0.16.0). Use WSL2 meanwhile";
const UNSUPPORTED_REASON = {
  "win32-x64": WINDOWS_REASON,
  "win32-arm64": WINDOWS_REASON,
};

/**
 * Resolve the host to a release target.
 * @returns {{key: string, pkg: string, cpu: string}} the platform package to load. Always the
 * host's own `<platform>-<arch>`: there is no cross-architecture mapping.
 * @throws if this host has no release target.
 */
function resolveTarget() {
  const key = `${process.platform}-${process.arch}`;
  if (SUPPORTED[key]) return { key, pkg: SUPPORTED[key], cpu: process.arch };
  const reason = UNSUPPORTED_REASON[key];
  throw new Error(
    `${PKG}: unsupported platform '${key}'` +
      (reason ? ` — ${reason}` : "") +
      `. Prebuilt platforms: ${Object.keys(SUPPORTED).join(", ")}.`,
  );
}

/** Absolute path to the `zigapagos` binary for this host. */
function binaryPath() {
  const { pkg } = resolveTarget();
  try {
    return require.resolve(`${pkg}/zigapagos`);
  } catch (err) {
    // ONLY a genuine "it is not there" becomes install advice. require.resolve also
    // throws for an `exports` map that hides the path
    // (ERR_PACKAGE_PATH_NOT_EXPORTED), a malformed package.json, or a permissions
    // error — all of them mis-packaging or environment problems, and rewriting them
    // as "reinstall without --omit=optional" sends the reader after the wrong thing.
    // Rethrow those untouched, with their own code and message.
    if (err && err.code !== "MODULE_NOT_FOUND") throw err;
    throw new Error(
      `${PKG}: the '${pkg}' package is not installed. If you installed with ` +
        `--no-optional or --omit=optional, reinstall without it so the platform ` +
        `binary is fetched.`,
    );
  }
}

/**
 * Absolute path to the bundled `@z/runtime` + Bun-sidecar tree, or null when this
 * install does not have one.
 *
 * The binary is told about this through `ZIGAPAGOS_RUNTIME_DIR` (see
 * `src/cli/release.zig`), which is what lets an npm-only install SSR and bundle
 * islands: without it the binary has no sidecar script to spawn and no
 * `browser-entry.ts` to build the shared client runtime from.
 *
 * Nullable rather than throwing, because "no bundled runtime" is a legitimate
 * state — a `zig build` checkout passes the paths explicitly and a hand-built
 * binary has none — and because a content-only site never needs it. The failure
 * for an islands site is then reported by the binary, naming the sidecar, rather
 * than by this launcher naming an environment variable the user never set.
 */
function runtimeDir() {
  const dir = join(__dirname, "runtime");
  return existsSync(join(dir, "sidecar", "standalone.ts")) ? dir : null;
}

/**
 * The `node_modules/.bin` directories belonging to this install, nearest first.
 *
 * WHY THE LAUNCHER TOUCHES `PATH` AT ALL. `bun` and `@zigbase/server` are
 * dependencies of this package, so npm puts their shims in a `.bin` directory —
 * but it only puts that directory on `PATH` for `npm run` scripts and `npx`. A
 * bare `zigapagos dev`, and every `npm i -g zigapagos`, would not see them, and
 * the two tools we just installed would be reported missing. Adding them here
 * makes the guarantee "installing zigapagos gets you a working dev loop" true
 * for every way of invoking it, not only the two npm happens to special-case.
 *
 * Walking up for each `node_modules` ancestor rather than assuming one location
 * is what makes this work under both a hoisted npm tree (the shims land in the
 * project root's `.bin`) and a nested/pnpm one (beside this package).
 */
function binDirs() {
  const dirs = [join(__dirname, "node_modules", ".bin")];
  for (let d = __dirname; ; ) {
    const parent = dirname(d);
    if (parent === d) break;
    if (basename(d) === "node_modules") dirs.push(join(d, ".bin"));
    d = parent;
  }
  return dirs.filter((d) => existsSync(d));
}

/**
 * The environment the binary is spawned with: this process's, plus the bundled
 * runtime's location, plus our `.bin` directories APPENDED to `PATH`.
 *
 * Appended, never prepended. The zigbase locator's first two steps are
 * `--zigbase=PATH` and a `PATH` scan, and a user who put a zigbase (or a bun) on
 * their `PATH` deliberately must keep winning — this only adds a fallback for the
 * case where there would otherwise be nothing. So existing behaviour is unchanged
 * wherever it already worked.
 */
function childEnv(env = process.env) {
  const out = { ...env };
  const dir = runtimeDir();
  if (dir) out.ZIGAPAGOS_RUNTIME_DIR = dir;
  const extra = binDirs();
  if (extra.length > 0) {
    // Preserve the caller's own spelling of the variable: on Windows it may be
    // `Path`, and adding a second `PATH` key would leave the original in force.
    const key = Object.keys(out).find((k) => k.toUpperCase() === "PATH") ?? "PATH";
    out[key] = [out[key], ...extra].filter(Boolean).join(delimiter);
  }
  return out;
}

module.exports = { binaryPath, resolveTarget, runtimeDir, binDirs, childEnv };
