// Generated by `zigapagos migrate --from rails`.
// Keep the action grammar in sync with port.actionDescriptors.
function ownerOf(root: HTMLElement, id: string): HTMLElement {
  return root.matches(`[data-controller~="${id}"]`) ? root : root.querySelector<HTMLElement>(`[data-controller~="${id}"]`) ?? root;
}

export function targetsOf(root: HTMLElement, id: string, names: string[]) {
  const owner = ownerOf(root, id);
  const out: Record<string, HTMLElement[]> = {};
  for (const name of names) out[name] = [owner, ...owner.querySelectorAll<HTMLElement>(`[data-${id}-target~="${name}"]`)]
    .filter(el => el.matches(`[data-${id}-target~="${name}"]`) && el.closest(`[data-controller~="${id}"]`) === owner);
  return out;
}

export function valuesOf(root: HTMLElement, id: string, types: Record<string, string>) {
  const owner = ownerOf(root, id);
  const out: Record<string, unknown> = {};
  for (const [name, type] of Object.entries(types)) {
    const raw = owner.getAttribute(`data-${id}-${name}-value`);
    if (raw === null) continue;
    out[name] = type === "boolean" ? raw !== "0" && raw !== "false" : type === "number" ? Number(raw.replaceAll("_", "")) : type === "array" || type === "object" ? JSON.parse(raw) : raw;
  }
  return out;
}

export function classesOf(root: HTMLElement, id: string, names: string[]) {
  const owner = ownerOf(root, id);
  const out: Record<string, string> = {};
  for (const name of names) {
    const value = owner.getAttribute(`data-${id}-${name}-class`);
    if (value !== null) out[name] = value;
  }
  return out;
}

const keys: Record<string, string> = {
  enter: "Enter", tab: "Tab", esc: "Escape", space: " ", up: "ArrowUp", down: "ArrowDown",
  left: "ArrowLeft", right: "ArrowRight", home: "Home", end: "End", page_up: "PageUp", page_down: "PageDown",
};
const modifiers = ["alt", "ctrl", "meta", "shift"] as const;
function matchesKey(event: Event, filter: string): boolean {
  if (!(event instanceof KeyboardEvent)) return false;
  const parts = filter.split("+");
  if (modifiers.some(name => event[`${name}Key`] !== parts.includes(name))) return false;
  const key = parts.find(part => !(modifiers as readonly string[]).includes(part));
  return key === undefined || event.key.toLowerCase() === (keys[key] ?? key).toLowerCase();
}

export function bindActions(root: HTMLElement, id: string, handlers: Record<string, (event: Event) => void>) {
  const owner = ownerOf(root, id);
  const removers: Array<() => void> = [];
  for (const el of [owner, ...owner.querySelectorAll<HTMLElement>("[data-action]")]) {
    const scope = el.closest(`[data-controller~="${id}"]`);
    if (scope && scope !== owner) continue;
    for (const token of (el.getAttribute("data-action") ?? "").split(/\s+/)) {
      const match = token.match(/^(?:([^\s]+)->)?([^#]+)#([$\w]+)((?::!?\w+)*)$/);
      if (!match || match[2] !== id || !Object.prototype.hasOwnProperty.call(handlers, match[3])) continue;
      const [spec, global] = (match[1] ?? "").split("@");
      const [explicit, filter] = spec.split(".");
      const event = explicit || (el.tagName === "INPUT" && (el as HTMLInputElement).type === "submit" ? "click" :
        ({ A: "click", BUTTON: "click", DETAILS: "toggle", FORM: "submit", INPUT: "input", SELECT: "change", TEXTAREA: "input" } as Record<string, string>)[el.tagName] ?? "click");
      const target = global === "window" ? window : global === "document" ? document : el;
      const options: AddEventListenerOptions = {};
      const filters: string[] = [];
      for (const option of match[4].split(":").filter(Boolean)) {
        if (option === "capture" || option === "once" || option === "passive") options[option] = true;
        else if (option === "!passive") options.passive = false;
        else filters.push(option);
      }
      const wrapped = (e: Event) => {
        if (e.target instanceof Element && owner.contains(e.target)) {
          const eventScope = e.target.closest(`[data-controller~="${id}"]`);
          if (eventScope && eventScope !== owner) return;
        }
        if (filter && !matchesKey(e, filter)) return;
        for (const option of filters) {
          if (option === "self" && e.target !== el) return;
          if (option === "prevent") e.preventDefault();
          if (option === "stop") e.stopPropagation();
        }
        handlers[match[3]](e);
      };
      target.addEventListener(event, wrapped, options);
      removers.push(() => target.removeEventListener(event, wrapped, options));
    }
  }
  return () => { for (const remove of removers) remove(); };
}
