#!/usr/bin/env bash
# End-to-end contract for every non-Astro migration adapter: detection,
# inventory, deterministic React/content conversion, review metadata, source
# immutability, and non-clobbering repeat runs.
set -euo pipefail
cd "$(dirname "$0")/../.."
REPO="$(pwd)"
ZIGAPAGOS="${ZIGAPAGOS:-$REPO/zig-out/bin/zigapagos}"

fail() { echo "FAIL: $*"; exit 1; }
if [[ ! -x "$ZIGAPAGOS" ]]; then
  mise exec -- zig build || fail "zig build failed"
fi

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# Next.js: no next.config file on purpose. Detection must use package.json,
# and a colocated App Router client module must become a scaffold candidate.
NEXT="$WORK/next"
mkdir -p "$NEXT/src/app/dashboard" "$NEXT/public/img"
cat > "$NEXT/package.json" <<'JSON'
{"dependencies":{"next":"16.0.0","react":"19.0.0"}}
JSON
cat > "$NEXT/src/app/dashboard/Chart.tsx" <<'TSX'
"use client";
import { useState } from "react";
export default function Chart() {
  const [n] = useState(1);
  return <output>{n}</output>;
}
TSX
cat > "$NEXT/src/app/dashboard/page.tsx" <<'TSX'
"use client";
export default function Dashboard() { return <main>Dashboard</main>; }
TSX
cat > "$NEXT/src/app/dashboard/route.ts" <<'TS'
"use client";
export function GET() { return new Response("ok"); }
TS
printf 'next-logo\n' > "$NEXT/public/img/logo.txt"
truncate -s 17825792 "$NEXT/public/large-media.bin"
NEXT_BEFORE="$(sha256sum "$NEXT/src/app/dashboard/Chart.tsx" | cut -d' ' -f1)"
NEXT_ASSET_BEFORE="$(sha256sum "$NEXT/public/img/logo.txt" | cut -d' ' -f1)"
"$ZIGAPAGOS" migrate "$NEXT" --scaffold "$WORK/next-components" --copy-assets "$WORK/next-assets" -o "$WORK/NEXT-MIGRATION.md"
grep -q 'Next.js' "$WORK/NEXT-MIGRATION.md" || fail "Next.js was not auto-detected"
grep -Fq 'Generated by `zigapagos migrate`.' "$WORK/NEXT-MIGRATION.md" || fail "report does not describe auto-detected invocation accurately"
! grep -Fq 'Generated by `zigapagos migrate --from' "$WORK/NEXT-MIGRATION.md" || fail "auto-detected report claims --from was passed"
grep -q 'src/app/dashboard/Chart.tsx' "$WORK/NEXT-MIGRATION.md" || fail "use client module missing from worklist"
grep -q 'from "@z/runtime"' "$WORK/next-components/Chart.island.tsx" || fail "React import was not converted"
[[ ! -e "$WORK/next-components/page.island.tsx" ]] || fail "client-marked App Router page was scaffolded as an island"
grep -q 'src/app/dashboard/page.tsx' "$WORK/NEXT-MIGRATION.md" || fail "client-marked App Router page missing from routes"
grep -q 'src/app/dashboard/route.ts' "$WORK/NEXT-MIGRATION.md" || fail "App Router route handler missing from routes"
grep -q 'Conventional public/static asset copy was requested' "$WORK/NEXT-MIGRATION.md" || fail "report omitted requested asset copy"
grep -xF 'next-logo' "$WORK/next-assets/img/logo.txt" || fail "Next.js public asset was not copied at its URL path"
[[ "$(wc -c < "$WORK/next-assets/large-media.bin")" == 17825792 ]] || fail "large Next.js asset was truncated or skipped"
"$ZIGAPAGOS" migrate "$NEXT" --copy-assets "$WORK/next-assets" -o "$WORK/NEXT-MIGRATION-2.md"
[[ -f "$WORK/next-assets/img/logo.txt.new" ]] || fail "repeat asset copy clobbered instead of writing .new"
/usr/bin/diff -q "$WORK/next-assets/img/logo.txt" "$WORK/next-assets/img/logo.txt.new" >/dev/null || fail "versioned asset copy differs"
NEXT_AFTER="$(sha256sum "$NEXT/src/app/dashboard/Chart.tsx" | cut -d' ' -f1)"
[[ "$NEXT_BEFORE" == "$NEXT_AFTER" ]] || fail "Next.js source was modified"
NEXT_ASSET_AFTER="$(sha256sum "$NEXT/public/img/logo.txt" | cut -d' ' -f1)"
[[ "$NEXT_ASSET_BEFORE" == "$NEXT_ASSET_AFTER" ]] || fail "Next.js public asset source was modified"

BAD_ASSET_ROOT="$WORK/bad-asset-root"
mkdir -p "$BAD_ASSET_ROOT"
printf '%s\n' '{"dependencies":{"next":"16.0.0"}}' > "$BAD_ASSET_ROOT/package.json"
printf 'not a directory\n' > "$BAD_ASSET_ROOT/public"
if "$ZIGAPAGOS" migrate "$BAD_ASSET_ROOT" --copy-assets "$WORK/bad-assets" -o "$WORK/BAD-ASSET-MIGRATION.md" >"$WORK/bad-assets.log" 2>&1; then
  fail "asset copy silently accepted a conventional root that was not a directory"
fi
grep -q "error accessing dir 'public'" "$WORK/bad-assets.log" || fail "invalid asset root did not produce an actionable error"

# Gatsby: config detection and conventional React components share the real
# scaffold path rather than receiving a placeholder-only implementation.
GATSBY="$WORK/gatsby"
mkdir -p "$GATSBY/src/pages" "$GATSBY/src/components" "$GATSBY/static"
: > "$GATSBY/gatsby-config.js"
cat > "$GATSBY/src/pages/index.jsx" <<'JSX'
export default function Home() { return <main>Home</main>; }
JSX
cat > "$GATSBY/src/components/Signup.js" <<'JSX'
import React, { useState } from "react";
export default function Signup() {
  const [email] = useState("");
  return <output>{email}</output>;
}
JSX
printf 'gatsby-icon\n' > "$GATSBY/static/favicon.ico"
"$ZIGAPAGOS" migrate "$GATSBY" --scaffold "$WORK/gatsby-components" --copy-assets "$WORK/gatsby-assets" -o "$WORK/GATSBY-MIGRATION.md"
grep -q 'Gatsby' "$WORK/GATSBY-MIGRATION.md" || fail "Gatsby was not auto-detected"
grep -q 'src/pages/index.jsx' "$WORK/GATSBY-MIGRATION.md" || fail "Gatsby page missing from worklist"
grep -q 'from "@z/runtime"' "$WORK/gatsby-components/Signup.island.tsx" || fail "Gatsby .js React import was not converted"
grep -xF 'gatsby-icon' "$WORK/gatsby-assets/favicon.ico" || fail "Gatsby static asset was not copied at its URL path"

# Nuxt/Vue: package fallback detection and all conventional source groups must
# be inventoried, while the report remains honest that Vue semantics need a port.
NUXT="$WORK/nuxt"
mkdir -p "$NUXT/pages" "$NUXT/components" "$NUXT/public"
cat > "$NUXT/package.json" <<'JSON'
{"dependencies":{"nuxt":"4.0.0","vue":"3.5.0"}}
JSON
cat > "$NUXT/pages/index.vue" <<'VUE'
<template><main>Home</main></template>
VUE
cat > "$NUXT/components/Signup.vue" <<'VUE'
<script setup>const email = ref("")</script>
<template><output>{{ email }}</output></template>
VUE
printf 'nuxt-robots\n' > "$NUXT/public/robots.txt"
"$ZIGAPAGOS" migrate "$NUXT" --copy-assets "$WORK/nuxt-assets" -o "$WORK/NUXT-MIGRATION.md"
grep -q 'Nuxt/Vue' "$WORK/NUXT-MIGRATION.md" || fail "Nuxt was not auto-detected"
grep -q 'pages/index.vue' "$WORK/NUXT-MIGRATION.md" || fail "Nuxt page missing from worklist"
grep -q 'components/Signup.vue' "$WORK/NUXT-MIGRATION.md" || fail "Vue component missing from worklist"
grep -q 'Vue SFCs are not mechanically rewritten' "$WORK/NUXT-MIGRATION.md" || fail "Nuxt report overclaims automatic conversion"
grep -xF 'nuxt-robots' "$WORK/nuxt-assets/robots.txt" || fail "Nuxt public asset was not copied at its URL path"

# Plain Vue has no Nuxt directory contract. Its complete src/**/*.vue tree,
# including a root-level App.vue, must still be visible in the worklist.
VUE="$WORK/vue"
mkdir -p "$VUE/src/features"
cat > "$VUE/package.json" <<'JSON'
{"dependencies":{"vue":"3.5.0"}}
JSON
cat > "$VUE/src/App.vue" <<'VUE'
<template><main>App</main></template>
VUE
cat > "$VUE/src/features/Room.vue" <<'VUE'
<template><section>Room</section></template>
VUE
"$ZIGAPAGOS" migrate "$VUE" --copy-assets "$WORK/vue-assets" -o "$WORK/VUE-MIGRATION.md" >"$WORK/vue.log" 2>&1
grep -q 'src/App.vue' "$WORK/VUE-MIGRATION.md" || fail "plain Vue App.vue missing from worklist"
grep -q 'src/features/Room.vue' "$WORK/VUE-MIGRATION.md" || fail "plain Vue nested SFC missing from worklist"
grep -q 'REVIEW no conventional public/static asset root was found' "$WORK/vue.log" || fail "missing Vue asset root was not made review-visible"
if "$ZIGAPAGOS" migrate "$VUE" --scaffold "$WORK/vue-components" -o "$WORK/VUE-SCAFFOLD.md" >"$WORK/vue-scaffold.log" 2>&1; then
  fail "Vue accepted unsupported --scaffold conversion"
fi
grep -q 'Usage: zigapagos migrate' "$WORK/vue-scaffold.log" || fail "unsupported --scaffold error omitted command usage"

if "$ZIGAPAGOS" migrate "$NEXT" --convert-content "$WORK/next-content" -o "$WORK/NEXT-CONTENT.md" >"$WORK/next-content.log" 2>&1; then
  fail "Next.js accepted unsupported --convert-content conversion"
fi
grep -q 'Usage: zigapagos migrate' "$WORK/next-content.log" || fail "unsupported --convert-content error omitted command usage"

# Hugo: YAML frontmatter becomes Ziggy, the Markdown body survives byte content,
# _index routing is normalized, and a repeat run versions rather than overwrites.
HUGO="$WORK/hugo"
mkdir -p "$HUGO/content/blog" "$HUGO/layouts" "$HUGO/static/media"
: > "$HUGO/hugo.toml"
cat > "$HUGO/content/blog/_index.md" <<'MD'
---
title: "Journal"
date: 2026-08-15
draft: true
---
# Preserved body
MD
printf 'hugo-media\n' > "$HUGO/static/media/photo.txt"
HUGO_BEFORE="$(sha256sum "$HUGO/content/blog/_index.md" | cut -d' ' -f1)"
"$ZIGAPAGOS" migrate "$HUGO" --convert-content "$WORK/hugo-content" --copy-assets "$WORK/hugo-assets" -o "$WORK/HUGO-MIGRATION.md"
OUT="$WORK/hugo-content/blog/index.smd"
grep -xF '.title = "Journal",' "$OUT" || fail "Hugo title was not normalized"
grep -xF '.date = @date("2026-08-15T00:00:00"),' "$OUT" || fail "Hugo date was not normalized"
grep -xF '.draft = true,' "$OUT" || fail "Hugo draft was not normalized"
grep -xF '# Preserved body' "$OUT" || fail "Hugo Markdown body was not preserved"
grep -q 'migration_review = true' "$OUT" || fail "review marker missing"
grep -xF 'hugo-media' "$WORK/hugo-assets/media/photo.txt" || fail "Hugo static asset was not copied at its URL path"
VALIDATE="$WORK/validate"
mkdir -p "$VALIDATE/content/blog"
cp -r tests/rendering/simple/layouts "$VALIDATE/"
cp tests/rendering/simple/zigapagos.ziggy "$VALIDATE/"
cp tests/rendering/simple/content/index.smd "$VALIDATE/content/"
cp "$OUT" "$VALIDATE/content/blog/index.smd"
( cd "$VALIDATE" && "$ZIGAPAGOS" validate ) || fail "converted Hugo content is not valid Zigapagos input"
"$ZIGAPAGOS" migrate "$HUGO" --convert-content "$WORK/hugo-content" -o "$WORK/HUGO-MIGRATION-2.md"
[[ -f "$OUT.new" ]] || fail "repeat conversion clobbered instead of writing .new"
/usr/bin/diff -q "$OUT" "$OUT.new" >/dev/null || fail "versioned conversion differs"
HUGO_AFTER="$(sha256sum "$HUGO/content/blog/_index.md" | cut -d' ' -f1)"
[[ "$HUGO_BEFORE" == "$HUGO_AFTER" ]] || fail "Hugo source was modified"

# Jekyll: dated post paths, published state, and unknown/invalid metadata are
# all carried into a valid target instead of being silently discarded.
JEKYLL="$WORK/jekyll"
mkdir -p "$JEKYLL/_posts" "$JEKYLL/_includes" "$JEKYLL/assets/img"
: > "$JEKYLL/_config.yml"
cat > "$JEKYLL/_posts/2026-08-15-hello.md" <<'MD'
---
title: Hello
date: 2026-02-30
published: false
permalink: /hello/
tags: [news]
---
# Jekyll body
MD
cat > "$JEKYLL/_includes/card.html" <<'HTML'
<article>{{ include.title }}</article>
HTML
printf 'jekyll-image\n' > "$JEKYLL/assets/img/card.txt"
printf '%s\n' '---' '---' '.site { color: red; }' > "$JEKYLL/assets/main.scss"
JEKYLL_LOG="$WORK/jekyll.log"
"$ZIGAPAGOS" migrate "$JEKYLL" --convert-content "$WORK/jekyll-content" --copy-assets "$WORK/jekyll-assets" -o "$WORK/JEKYLL-MIGRATION.md" >"$JEKYLL_LOG" 2>&1
JEKYLL_OUT="$WORK/jekyll-content/posts/2026-08-15-hello.smd"
grep -q 'Jekyll' "$WORK/JEKYLL-MIGRATION.md" || fail "Jekyll was not auto-detected"
grep -q '_includes/card.html' "$WORK/JEKYLL-MIGRATION.md" || fail "Jekyll include missing from worklist"
grep -xF '.draft = true,' "$JEKYLL_OUT" || fail "Jekyll published state was not converted"
grep -q 'migration_frontmatter' "$JEKYLL_OUT" || fail "unconverted Jekyll frontmatter was discarded"
grep -q 'permalink: /hello/' "$JEKYLL_OUT" || fail "Jekyll permalink was not preserved for review"
grep -q 'migration_invalid_date = "2026-02-30"' "$JEKYLL_OUT" || fail "invalid Jekyll date was not preserved"
grep -q 'REVIEW .*unconverted frontmatter' "$JEKYLL_LOG" || fail "unconverted frontmatter warning was not printed"
grep -q 'REVIEW .*invalid date' "$JEKYLL_LOG" || fail "invalid date warning was not printed"
grep -xF 'jekyll-image' "$WORK/jekyll-assets/assets/img/card.txt" || fail "Jekyll asset path lost its public assets/ prefix"
[[ ! -e "$WORK/jekyll-assets/assets/main.scss" ]] || fail "Jekyll pipeline SCSS was copied as a public static asset"
mkdir -p "$VALIDATE/content/posts"
cp tests/rendering/simple/content/index.smd "$VALIDATE/content/posts/index.smd"
cp "$JEKYLL_OUT" "$VALIDATE/content/posts/2026-08-15-hello.smd"
( cd "$VALIDATE" && "$ZIGAPAGOS" validate ) || fail "converted Jekyll review metadata is not valid Zigapagos input"

HELP="$WORK/help.txt"
"$ZIGAPAGOS" help >"$HELP" 2>&1
grep -q 'Scan a supported framework' "$HELP" || fail "top-level help still describes migrate as Astro-only"
MIGRATE_HELP="$WORK/migrate-help.txt"
"$ZIGAPAGOS" migrate --help >"$MIGRATE_HELP" 2>&1
grep -q 'nuxt|vue' "$MIGRATE_HELP" || fail "migrate help omits the supported --from vue alias"
grep -q 'Astro, Next.js, and Gatsby React' "$MIGRATE_HELP" || fail "migrate help omits the --scaffold source constraint"

# Eleventy: conventional config detection, private template inventory, and
# Markdown conversion coexist without treating _includes/_layouts as pages.
ELEVENTY="$WORK/eleventy"
mkdir -p "$ELEVENTY/src/_includes" "$ELEVENTY/src/_layouts" "$ELEVENTY/src/_data" "$ELEVENTY/src/writing" "$ELEVENTY/public"
: > "$ELEVENTY/.eleventy.js"
cat > "$ELEVENTY/package.json" <<'JSON'
{"devDependencies":{"@11ty/eleventy":"3.1.5"}}
JSON
cat > "$ELEVENTY/src/writing/hello.md" <<'MD'
---
title: Hello 11ty
layout: base.njk
permalink: /hello/
---
# Eleventy body
MD
: > "$ELEVENTY/src/_includes/card.njk"
: > "$ELEVENTY/src/_layouts/base.njk"
echo '{"siteName":"Example"}' > "$ELEVENTY/src/_data/site.json"
printf 'eleventy-icon\n' > "$ELEVENTY/public/favicon.ico"
"$ZIGAPAGOS" migrate "$ELEVENTY" --convert-content "$WORK/eleventy-content" --copy-assets "$WORK/eleventy-assets" -o "$WORK/ELEVENTY-MIGRATION.md"
ELEVENTY_OUT="$WORK/eleventy-content/writing/hello.smd"
grep -q 'Eleventy (11ty)' "$WORK/ELEVENTY-MIGRATION.md" || fail "Eleventy was not auto-detected"
grep -q 'src/_includes/card.njk' "$WORK/ELEVENTY-MIGRATION.md" || fail "Eleventy include missing from worklist"
grep -q 'src/_layouts/base.njk' "$WORK/ELEVENTY-MIGRATION.md" || fail "Eleventy layout missing from worklist"
grep -q 'src/_data/site.json' "$WORK/ELEVENTY-MIGRATION.md" || fail "Eleventy data file missing from worklist"
[[ "$(grep -c 'src/_includes/card.njk' "$WORK/ELEVENTY-MIGRATION.md")" == 1 ]] || fail "Eleventy include was also misclassified as a page"
grep -q 'permalink: /hello/' "$ELEVENTY_OUT" || fail "Eleventy permalink was not preserved for review"
grep -xF '# Eleventy body' "$ELEVENTY_OUT" || fail "Eleventy Markdown body was not preserved"
grep -xF 'eleventy-icon' "$WORK/eleventy-assets/favicon.ico" || fail "Eleventy public asset was not copied at its URL path"

# Hexo: package/structure disambiguates its shared _config.yml name from
# Jekyll, source/_posts paths normalize, drafts stay drafts, and theme EJS is
# inventoried without claiming template conversion.
HEXO="$WORK/hexo"
mkdir -p "$HEXO/source/_posts" "$HEXO/source/_drafts" "$HEXO/source/images" "$HEXO/themes/daily/layout"
: > "$HEXO/_config.yml"
cat > "$HEXO/package.json" <<'JSON'
{"dependencies":{"hexo":"7.3.0"}}
JSON
cat > "$HEXO/source/_posts/hello.md" <<'MD'
---
title: Hello Hexo
tags: [news]
categories: [writing]
---
# Hexo body
<!-- more -->
<blockquote>
  A quotation
  <footer>--Author</footer>
</blockquote>
MD
cat > "$HEXO/source/_drafts/idea.md" <<'MD'
---
title: An idea
---
Draft body
MD
printf 'hexo-image\n' > "$HEXO/source/images/photo.txt"
mkdir -p "$HEXO/source/_posts/hello"
printf 'relocated-post-image\n' > "$HEXO/source/_posts/hello/photo.txt"
: > "$HEXO/themes/daily/layout/post.ejs"
"$ZIGAPAGOS" migrate "$HEXO" --convert-content "$WORK/hexo-content" --copy-assets "$WORK/hexo-assets" -o "$WORK/HEXO-MIGRATION.md"
grep -q 'Hexo' "$WORK/HEXO-MIGRATION.md" || fail "Hexo was not auto-detected"
grep -q 'themes/daily/layout/post.ejs' "$WORK/HEXO-MIGRATION.md" || fail "Hexo theme layout missing from worklist"
grep -q 'tags: \[news\]' "$WORK/hexo-content/posts/hello.smd" || fail "Hexo tags were not preserved for review"
grep -xF '.draft = true,' "$WORK/hexo-content/drafts/idea.smd" || fail "Hexo draft directory was not preserved"
! grep -q '<!-- more -->' "$WORK/hexo-content/posts/hello.smd" || fail "Hexo excerpt marker survived conversion"
grep -xF '> A quotation' "$WORK/hexo-content/posts/hello.smd" || fail "Hexo blockquote was not normalized"
grep -xF 'hexo-image' "$WORK/hexo-assets/images/photo.txt" || fail "Hexo static source asset was not copied at its URL path"
[[ ! -e "$WORK/hexo-assets/_posts/hello.md" ]] || fail "Hexo Markdown source was copied as a static asset"
[[ ! -e "$WORK/hexo-assets/_posts/hello/photo.txt" ]] || fail "Hexo config-routed post asset was copied at a false /_posts URL"
mkdir -p "$VALIDATE/content/writing" "$VALIDATE/content/drafts"
cp tests/rendering/simple/content/index.smd "$VALIDATE/content/writing/index.smd"
cp tests/rendering/simple/content/index.smd "$VALIDATE/content/drafts/index.smd"
cp "$ELEVENTY_OUT" "$VALIDATE/content/writing/hello.smd"
cp "$WORK/hexo-content/posts/hello.smd" "$VALIDATE/content/posts/hello.smd"
cp "$WORK/hexo-content/drafts/idea.smd" "$VALIDATE/content/drafts/idea.smd"
( cd "$VALIDATE" && "$ZIGAPAGOS" validate ) || fail "converted Eleventy/Hexo content is not valid Zigapagos input"

# A bare _config.yml is shared by multiple ecosystems and cannot be identified
# confidently. Refuse to guess, print actionable usage, and do not panic.
UNKNOWN="$WORK/unknown"
mkdir -p "$UNKNOWN"
: > "$UNKNOWN/_config.yml"
if "$ZIGAPAGOS" migrate "$UNKNOWN" -o "$WORK/UNKNOWN.md" >"$WORK/unknown.log" 2>&1; then
  fail "unidentifiable _config.yml was guessed instead of requesting --from"
fi
grep -q 'ask the project owner or pass --from' "$WORK/unknown.log" || fail "failed detection did not provide an actionable choice"
grep -q 'Usage: zigapagos migrate' "$WORK/unknown.log" || fail "failed detection omitted command usage"
! grep -q 'Zigapagos debug stack trace' "$WORK/unknown.log" || fail "failed detection panicked instead of exiting as a usage error"

# Multiple positive framework markers are genuinely ambiguous. Treat this as
# project/user input too, with the same clean --from escape hatch.
AMBIGUOUS="$WORK/ambiguous"
mkdir -p "$AMBIGUOUS"
: > "$AMBIGUOUS/astro.config.mjs"
: > "$AMBIGUOUS/next.config.mjs"
if "$ZIGAPAGOS" migrate "$AMBIGUOUS" -o "$WORK/AMBIGUOUS.md" >"$WORK/ambiguous.log" 2>&1; then
  fail "multiple framework markers were guessed instead of requesting --from"
fi
grep -q 'multiple source frameworks detected' "$WORK/ambiguous.log" || fail "ambiguous detection omitted the conflicting-framework error"
grep -q 'Usage: zigapagos migrate' "$WORK/ambiguous.log" || fail "ambiguous detection omitted command usage"
! grep -q 'Zigapagos debug stack trace' "$WORK/ambiguous.log" || fail "ambiguous detection panicked instead of exiting as a usage error"

echo "PASS: Next.js, Gatsby, Nuxt/Vue, Hugo, Jekyll, Eleventy, and Hexo migration adapters"
