import { test, expect } from "bun:test";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { apiGen, apiCheck, extractSchemaHash, type Runner } from "./apiclient.ts";
import type { CodegenConfig } from "./codegen-config.ts";

const HEADER = (hash: string) => `// generated by zigbase — do not edit\n// schema-hash: ${hash}\nexport const x = 1;\n`;

function scratch() {
  return mkdtempSync(join(tmpdir(), "apiclient-"));
}

/** A config where the backend "produces" a file at producedPath under genClientCwd. */
function zbConfig(base: string): CodegenConfig {
  return {
    mode: "zigbase",
    zigbase: {
      genClientCmd: ["fake-gen", "client"],
      genClientCwd: join(base, "backend"),
      out: join(base, "app/contract/generated/zbase.gen.ts"),
      apiPrefix: "/api",
      producedPath: "clients/typescript/zbase.gen.ts",
    },
  };
}

test("extractSchemaHash pulls the hash from the header", () => {
  expect(extractSchemaHash(HEADER("a69ad90815793c2e"))).toBe("a69ad90815793c2e");
  expect(extractSchemaHash("no header here")).toBeNull();
});

test("api-gen invokes the configured cmd (mocked) + vendors producedPath -> out", () => {
  const base = scratch();
  try {
    const cfg = zbConfig(base);
    const zb = cfg.zigbase!;
    const producedAbs = join(zb.genClientCwd, zb.producedPath!);
    mkdirSync(zb.genClientCwd, { recursive: true });

    const calls: { cmd: string[]; cwd: string }[] = [];
    const runner: Runner = (cmd, cwd) => {
      calls.push({ cmd, cwd });
      // Simulate the backend gen-client writing its output.
      mkdirSync(join(zb.genClientCwd, "clients/typescript"), { recursive: true });
      writeFileSync(producedAbs, HEADER("deadbeef"));
    };

    apiGen(cfg, { runner, log: () => {} });

    // The configured cmd ran in genClientCwd.
    expect(calls).toHaveLength(1);
    expect(calls[0].cmd).toEqual(["fake-gen", "client"]);
    expect(calls[0].cwd).toBe(zb.genClientCwd);
    // The produced file was vendored into out.
    expect(existsSync(zb.out)).toBe(true);
    expect(readFileSync(zb.out, "utf8")).toBe(HEADER("deadbeef"));
  } finally {
    rmSync(base, { recursive: true, force: true });
  }
});

test("api-check PASSES when committed out matches fresh gen-client output", () => {
  const base = scratch();
  try {
    const cfg = zbConfig(base);
    const zb = cfg.zigbase!;
    const producedAbs = join(zb.genClientCwd, zb.producedPath!);
    mkdirSync(join(zb.genClientCwd, "clients/typescript"), { recursive: true });
    mkdirSync(join(base, "app/contract/generated"), { recursive: true });
    // committed out == what the backend will regenerate
    writeFileSync(zb.out, HEADER("matching"));

    const runner: Runner = () => writeFileSync(producedAbs, HEADER("matching"));
    expect(() => apiCheck(cfg, { runner, log: () => {} })).not.toThrow();
  } finally {
    rmSync(base, { recursive: true, force: true });
  }
});

test("api-check FAILS (drift) when backend output differs from committed out", () => {
  const base = scratch();
  try {
    const cfg = zbConfig(base);
    const zb = cfg.zigbase!;
    const producedAbs = join(zb.genClientCwd, zb.producedPath!);
    mkdirSync(join(zb.genClientCwd, "clients/typescript"), { recursive: true });
    mkdirSync(join(base, "app/contract/generated"), { recursive: true });
    writeFileSync(zb.out, HEADER("old-hash"));

    // Backend now regenerates a DIFFERENT client (schema changed).
    const runner: Runner = () => writeFileSync(producedAbs, HEADER("new-hash"));
    expect(() => apiCheck(cfg, { runner, log: () => {} })).toThrow(/DRIFT/);
    // Non-destructive: committed out is unchanged after the failed check.
    expect(readFileSync(zb.out, "utf8")).toBe(HEADER("old-hash"));
  } finally {
    rmSync(base, { recursive: true, force: true });
  }
});

test("api-check backend-absent fallback: PRESENCE gate passes loudly, cmd NOT run", () => {
  const base = scratch();
  try {
    const cfg = zbConfig(base); // genClientCwd (base/backend) does NOT exist
    const zb = cfg.zigbase!;
    mkdirSync(join(base, "app/contract/generated"), { recursive: true });
    writeFileSync(zb.out, HEADER("pinned"));

    const logs: string[] = [];
    let ran = false;
    const runner: Runner = () => {
      ran = true;
    };
    apiCheck(cfg, { runner, log: (m) => logs.push(m) });

    expect(ran).toBe(false); // backend absent => never invokes gen-client
    const joined = logs.join("\n");
    expect(joined).toMatch(/WARNING/);
    expect(joined).toMatch(/PRESENCE gate/);
    expect(joined).toMatch(/pinned/); // logs the schema-hash
  } finally {
    rmSync(base, { recursive: true, force: true });
  }
});

test("api-check backend-absent + missing committed client => hard FAIL (not silent)", () => {
  const base = scratch();
  try {
    const cfg = zbConfig(base); // backend absent, out never written
    expect(() => apiCheck(cfg, { runner: () => {}, log: () => {} })).toThrow(/missing/);
  } finally {
    rmSync(base, { recursive: true, force: true });
  }
});

// ── Direct-write path (no producedPath): the command writes `out` in place. ─────
// A backend that accepts an app-tree --out omits producedPath, so produced===out.

/** A direct-write config: no producedPath => the command writes `out` directly. */
function directWriteConfig(base: string): CodegenConfig {
  return {
    mode: "zigbase",
    zigbase: {
      genClientCmd: ["fake-gen", "client"],
      genClientCwd: join(base, "backend"),
      out: join(base, "app/contract/generated/zbase.gen.ts"),
      apiPrefix: "/api",
      // no producedPath => produced === out (direct write)
    },
  };
}

test("api-check direct-write drift => DRIFT throw AND committed out restored byte-exact", () => {
  const base = scratch();
  try {
    const cfg = directWriteConfig(base);
    const zb = cfg.zigbase!;
    mkdirSync(zb.genClientCwd, { recursive: true }); // backend present
    mkdirSync(join(base, "app/contract/generated"), { recursive: true });
    writeFileSync(zb.out, HEADER("old-hash"));

    // Direct-write backend overwrites `out` in place with a different client.
    const runner: Runner = () => writeFileSync(zb.out, HEADER("new-hash"));
    expect(() => apiCheck(cfg, { runner, log: () => {} })).toThrow(/DRIFT/);
    // The committed out is restored to its exact original bytes, not the fresh output.
    expect(readFileSync(zb.out, "utf8")).toBe(HEADER("old-hash"));
  } finally {
    rmSync(base, { recursive: true, force: true });
  }
});

test("api-check direct-write, committed missing => hard FAIL AND no leftover file", () => {
  const base = scratch();
  try {
    const cfg = directWriteConfig(base);
    const zb = cfg.zigbase!;
    mkdirSync(zb.genClientCwd, { recursive: true }); // backend present
    mkdirSync(join(base, "app/contract/generated"), { recursive: true });
    // out is NOT committed (missing).

    // The direct-write backend creates `out` fresh.
    const runner: Runner = () => writeFileSync(zb.out, HEADER("fresh"));
    expect(() => apiCheck(cfg, { runner, log: () => {} })).toThrow(/missing/);
    // Zero-side-effect: the freshly-created file is removed before throwing.
    expect(existsSync(zb.out)).toBe(false);
  } finally {
    rmSync(base, { recursive: true, force: true });
  }
});

test("api-check direct-write, committed matches fresh => PASS (out unchanged)", () => {
  const base = scratch();
  try {
    const cfg = directWriteConfig(base);
    const zb = cfg.zigbase!;
    mkdirSync(zb.genClientCwd, { recursive: true });
    mkdirSync(join(base, "app/contract/generated"), { recursive: true });
    writeFileSync(zb.out, HEADER("same"));

    const runner: Runner = () => writeFileSync(zb.out, HEADER("same"));
    expect(() => apiCheck(cfg, { runner, log: () => {} })).not.toThrow();
    expect(readFileSync(zb.out, "utf8")).toBe(HEADER("same"));
  } finally {
    rmSync(base, { recursive: true, force: true });
  }
});

test("api-check direct-write: a gen-client that writes `out` then FAILS still restores the committed bytes", () => {
  const base = scratch();
  try {
    const cfg = directWriteConfig(base);
    const zb = cfg.zigbase!;
    mkdirSync(zb.genClientCwd, { recursive: true }); // backend present
    mkdirSync(join(base, "app/contract/generated"), { recursive: true });
    writeFileSync(zb.out, HEADER("committed"));

    // The realistic failure: gen-client emits a partial client and THEN exits
    // non-zero (execFileSync throws). The check must still leave the app tree
    // exactly as it found it — its documented "Non-destructive" guarantee.
    const runner: Runner = () => {
      writeFileSync(zb.out, "// partial backend output, then a crash\n");
      throw new Error("gen-client exited with status 1");
    };
    expect(() => apiCheck(cfg, { runner, log: () => {} })).toThrow(/gen-client exited/);
    expect(readFileSync(zb.out, "utf8")).toBe(HEADER("committed"));
  } finally {
    rmSync(base, { recursive: true, force: true });
  }
});

test("api-check direct-write: a failing gen-client with NOTHING committed leaves no untracked file", () => {
  const base = scratch();
  try {
    const cfg = directWriteConfig(base);
    const zb = cfg.zigbase!;
    mkdirSync(zb.genClientCwd, { recursive: true });
    mkdirSync(join(base, "app/contract/generated"), { recursive: true });
    // out is NOT committed.

    const runner: Runner = () => {
      writeFileSync(zb.out, "// partial backend output, then a crash\n");
      throw new Error("gen-client exited with status 1");
    };
    expect(() => apiCheck(cfg, { runner, log: () => {} })).toThrow(/gen-client exited/);
    expect(existsSync(zb.out)).toBe(false);
  } finally {
    rmSync(base, { recursive: true, force: true });
  }
});
